export const REPORTS_VIEW = "REPORTS";
export const SPENDING_VIEW = "SPENDING";
export const FINANCE_APPROVAL_VIEW = "FINANCE_APPROVAL";
export const APPROVAL_VIEW = "APPROVAL";
export const PAYMENT_PROCESSING_VIEW = "PAYMENT_PROCESSING";

export const categoryOptions = [
  { value: "AA_SESSION", label: "AA SESSION" },
  { value: "AMBULANCE_CHARGES", label: "AMBULANCE CHARGES" },
  { value: "AMC", label: "AMC" },
  { value: "BARBER_CHARGES", label: "BARBER CHARGES" },
  { value: "BEDS", label: "BEDS" },
  { value: "BMW_BILL", label: "BMW BILL" },
  { value: "CHECK", label: "CHECK" },
  { value: "CHICKEN_MUTTON", label: "CHICKEN / MUTTON" },
  { value: "CIVIL_WORK", label: "CIVIL WORK" },
  { value: "CONSULTANT_FEES", label: "CONSULTANT FEES" },
  { value: "COURIER", label: "COURIER" },
  { value: "DIAPERS", label: "DIAPERS" },
  { value: "ECG", label: "ECG" },
  { value: "ELECTRICAL_ITEM", label: "ELECTRICAL ITEM" },
  { value: "ELECTRICITY_BILL", label: "ELECTRICITY BILL" },
  { value: "FNF", label: "FNF" },
  { value: "FURNITURE", label: "FURNITURE" },
  { value: "FOOD", label: "FOOD" },
  { value: "GAS_CYLINDER", label: "GAS CYLINDER" },
  { value: "GROCERY", label: "GROCERY" },
  { value: "HOUSEKEEPING_MATERIAL", label: "HOUSE KEEPING MATERIAL" },
  { value: "INJECTIONS", label: "INJECTIONS" },
  { value: "LAB_CHARGES", label: "LAB CHARGES" },
  { value: "LAUNDRY", label: "LAUNDRY" },
  { value: "LICENSE_FEE", label: "LICENSE FEE" },
  { value: "MARKETING", label: "MARKETING" },
  { value: "MATTRESS", label: "MATTRESS" },
  { value: "MEDICAL_CONSUMABLES", label: "MEDICAL CONSUMABLES" },
  { value: "MEDICAL_EQUIPMENT", label: "MEDICAL EQUIPMENT" },
  { value: "MEDICINES", label: "MEDICINES" },
  { value: "NON_MEDICAL_EQUIPMENT", label: "NON MEDICAL EQUIPMENT" },
  { value: "OXYGEN_CYLINDER", label: "OXYGEN CYLINDER" },
  { value: "PATIENT_REFUND", label: "PATIENT REFUND" },
  { value: "PEST_CONTROL", label: "PEST CONTROL" },
  { value: "PRINTING", label: "PRINTING" },
  { value: "PROFESSIONAL_FEES", label: "PROFESSIONAL FEES" },
  { value: "PSYCHOLOGICAL_TEST", label: "PSYCHOLOGICAL TEST" },
  { value: "RENT", label: "RENT" },
  { value: "RENT_DG", label: "RENT - DG" },
  { value: "REPAIR_MAINTENANCE", label: "REPAIR & MAINTENANCE" },
  { value: "REIMBURSEMENT", label: "REIMBURSEMENT" },
  { value: "SALARY_ADVANCE", label: "SALARY ADVANCE" },
  { value: "STAFF_REFERRAL_PAYMENT", label: "STAFF REFERRAL PAYMENT" },
  { value: "SUBSCRIPTION_RECHARGE", label: "SUBSCRIPTION / RECHARGE" },
  { value: "THIRD_PARTY_MANPOWER", label: "THIRD PARTY MAN POWER" },
  { value: "TRAVELLING_CHARGES", label: "TRAVELLING CHARGES" },
  { value: "VACCINE", label: "VACCINE" },
  { value: "VEGETABLES_FRUITS", label: "VEGETABLES & FRUITS" },
  { value: "WATER_BILL", label: "WATER BILL" },
  { value: "WATER_PURIFIER", label: "WATER PURIFIER" },
  { value: "OTHERS", label: "OTHERS" },
];
