import React from "react";
import { Page, Document, StyleSheet, View, Text } from "@react-pdf/renderer";

import Table from "./Table";
import Header from "./Header";
import Footer from "./Footer";
import { format } from "date-fns";

const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 11,
    paddingTop: 30,
    paddingLeft: 60,
    paddingRight: 60,
    // paddingBottom: 30,
    flexDirection: "column",
  },
  row: {
    flexDirection: "row",
    width: "100%",
  },
  justifyBetween: {
    justifyContent: "space-between",
  },
});

const InvoiceNewTemplate = ({ bill, center, patient, admission }) => {
  console.log("Bill Type:", bill.bill);
  console.log("PDF BILL ID:", bill._id);
  const formatTimeDate = (datetime) =>
    datetime ? format(new Date(datetime), "hh:mm a 'on' dd/MM/yyyy") : "--";
  return (
    <React.Fragment>
      <Document>
        <Page size="A4" style={styles.page}>
          <Header
            patient={patient}
            center={center}
            bill={bill}
            admission={admission}
          />
          <Table bill={bill} />
          <Footer center={center} bill={bill} />
          <View
            style={{
              marginTop: "auto",
              fontSize: 8,
              paddingBottom: 20,
              paddingTop: 20,
            }}
            fixed
          >
            <View style={{ ...styles.row, ...styles.justifyBetween }}>
              <View style={{ ...styles.row }}>
                <Text style={styles.label}>Bill Generated By:&nbsp;</Text>
                <Text>
                  {bill.author?.name} at {formatTimeDate(bill.date)}
                </Text>
              </View>
              <View>
                <Text
                  render={({ pageNumber, totalPages }) =>
                    `Page ${pageNumber} of ${totalPages}`
                  }
                />
              </View>
            </View>
          </View>
        </Page>
      </Document>
    </React.Fragment>
  );
};

export default InvoiceNewTemplate;
